### INITIALIZATION
# INITIALIZE GAME:
#   INITIALIZE PLAY AREA
#   INITIALIZE PLAYERS:
#       INITIALIZE CHARACTERS
#       INITIALIZE BATTLEFIELD
#       INITIALIZE DECK

### GAME SETUP
# EACH PLAYER:
#   SHUFFLE DECK
#   DRAW 5 CARDS
#   MULLIGAN
#   GET 2 RESOURCES
#   ROLL CHARACTER DICE
# WINNING ROLL SELECTS BATTLEFIELD
# ASSERT BATTLEFIELD OWNERSHIP
# DEPLOY 2 SHIELDS

### PLAY GAME
# LOOP ROUNDS:
#   LOOP ACTION PHASE:
#       EACH PLAYER:
#           TAKE ONE ACTION (OR MORE)
#   UPKEEP PHASE:
#       READY EXHAUSTED CARDS
#       RETURN DICE IN POOL TO CARDS
#       GAIN 2 RESOURCES
#       DISCARD ANY NUMBER OF CARDS FROM HAND
#       IF POSSIBLE, DRAW HAND BACK UP TO MAX_HAND_SIZE

### POSSIBLE ACTIONS:
# PLAY A CARD FROM HAND:
#   PLAY AN EVENT
#   PLAY AN UPGRADE
#   PLAY A SUPPORT
# ACTIVATE A CHARACTER:
#   ROLL ALL CHARACTER/UPGRADE DICE
#   EXHAUST CHARACTER
# ACTIVATE A SUPPORT:
#   ROLL SUPPORT DIE
#   EXHAUST SUPPORT
# RESOLVE DICE:
#   SELECT SYMBOL TO RESOLVE
#   LOOP RESOLVE A DIE:
#       ADD ANY MODIFIER DICE?
# USE A CARD ACTION
# DISCARD TO REROLL:
#   SELECT CARD TO DISCARD
#   SELECT DICE TO REROLL
# CLAIM THE BATTLEFIELD:
#   TAKE CONTROL OF BATTLEFIELD
#   RESOLVE BATTLEFIELD ABILITY
# PASS

### WIN CONDITIONS:
# ALL CHARACTERS ARE DEFEATED
# NO CARDS IN HAND OR DECK AFTER UPKEEP PHASE
#   IF MILL TIE, BATTLEFIELD CONTROLLER WINS

### CARDS:
# AFFILIATION (HERO, VILLAIN, NEUTRAL)
# COLOUR (RED, BLUE, YELLOW, GREY)
# TYPE (BATTLEFIELD, CHARACTER, EVENT, UPGRADE, SUPPORT)
# SUBTYPE (WEAPON, EQUIPMENT, ABILITY, VEHICLE, DROID)
# (COST(S))
# (HEALTH)
# TITLE
# (SUBTITLE)
# (EFFECT(S))
# (ACTION(S))
# UNIQUE?
# (FLAVOUR TEXT)
# IMAGE
# ID (SET/NUMBER)
# RARITY
# DIE?
# READY?

### DICE:
# SIDES 1-6:
#   VALUE
#   SYMBOL/TYPE (MELEE, RANGED, SHIELD, RESOURCE, DISRUPT, DISCARD, FOCUS, SPECIAL, BLANK)
#   (COST)
#   MODIFIER?
#   ID (SET/NUMBER)
#   RARITY
# READY?

### PLAYER:
# CHARACTERS
# HAND
# DECK
# DISCARD_PILE
# BATTLEFIELD
# DICE POOL
# RESOURCES
# LIMBO
